{
	hotcity: [{
			cityName: '中国',
			pinyin: 'beijing',
			py: 'bj',
			code: '86'
		},
		{
			cityName: '日本',
			pinyin: 'shanghai',
			py: 'sh',
			code: '81'
		},
		{
			cityName: '天津',
			pinyin: 'tianjin',
			py: 'tj',
			code: 'tsn'
		},
		{
			cityName: '青岛',
			pinyin: 'qingdao',
			py: 'qd',
			code: 'tao'
		},
		{
			cityName: '南京',
			pinyin: 'nanjing',
			py: 'nj',
			code: 'nkg'
		},
		{
			cityName: '杭州',
			pinyin: 'hangzhou',
			py: 'hz',
			code: 'hgh'
		},
		{
			cityName: '厦门',
			pinyin: 'xiamen',
			py: 'xm',
			code: 'xmn'
		},
		{
			cityName: '成都',
			pinyin: 'chengdu',
			py: 'cd',
			code: 'ctu'
		},
		{
			cityName: '深圳',
			pinyin: 'shenzhen',
			py: 'sz',
			code: 'szx'
		},
		{
			cityName: '广州',
			pinyin: 'guangzhou',
			py: 'gz',
			code: 'can'
		},
		{
			cityName: '沈阳',
			pinyin: 'shenyang',
			py: 'sy',
			code: 'she'
		},
		{
			cityName: '武汉',
			pinyin: 'wuhan',
			py: 'wh',
			code: 'wuh'
		}
	],
	cities: [{
		"cityName": "Angola",
		"pinyin": "Angola",
		"py": "ao",
		"code": "244",
		// "sum":100
	}, {
		"cityName": "Afghanistan",
		"pinyin": "Afghanistan",
		"py": "af",
		"code": "93"
	}, {
		"cityName": "Albania",
		"pinyin": "Albania",
		"py": "al",
		"code": "355"
	}, {
		"cityName": "Algeria",
		"pinyin": "Algeria",
		"py": "Al",
		"code": "213"
	}, {
		"cityName": "Andorra",
		"pinyin": "Andorra",
		"py": "ad",
		"code": "376"
	}, {
		"cityName": "Anguilla",
		"pinyin": "Anguilla",
		"py": "ai",
		"code": "1264"
	}, {
		"cityName": "Antigua and barbuda",
		"pinyin": "Antigua and barbuda",
		"py": "ag",
		"code": "1268"
	}, {
		"cityName": "Argentina",
		"pinyin": "argentina",
		"py": "ar",
		"code": "54"
	}, {
		"cityName": "Armenia",
		"pinyin": "Armenia",
		"py": "am",
		"code": "374"
	}, {
		"cityName": "Ascension",
		"pinyin": "Ascension",
		"py": "asensong",
		"code": "247"
	}, {
		"cityName": "Australia",
		"pinyin": "australia",
		"py": "au",
		"code": "61"
	}, {
		"cityName": "Austria",
		"pinyin": "Austria",
		"py": "at",
		"code": "43"
	}, {
		"cityName": "Azerbaijan",
		"pinyin": "Azerbaijan",
		"py": "az",
		"code": "994"
	}, {
		"cityName": "Bahamas",
		"pinyin": "Bahamas",
		"py": "bs",
		"code": "1242"
	}, {
		"cityName": "Bahrain",
		"pinyin": "Bahrain",
		"py": "bh",
		"code": "973"
	}, {
		"cityName": "Bangladesh",
		"pinyin": "Bangladesh",
		"py": "bd",
		"code": "880"
	}, {
		"cityName": "Barbados",
		"pinyin": "Barbados",
		"py": "bb",
		"code": "1246"
	}, {
		"cityName": "Belarus",
		"pinyin": "Belarus",
		"py": "by",
		"code": "375"
	}, {
		"cityName": "Belgium",
		"pinyin": "Belgium",
		"py": "be",
		"code": "32	"
	}, {
		"cityName": "Belize",
		"pinyin": "Belize",
		"py": "bz",
		"code": "501"
	}, {
		"cityName": "Benin",
		"pinyin": "Benin",
		"py": "bj",
		"code": "229"
	}, {
		"cityName": "Bermuda is.",
		"pinyin": "Bermuda is.",
		"py": "bm",
		"code": "1441"
	}, {
		"cityName": "Bolivia",
		"pinyin": "Bolivia",
		"py": "bo",
		"code": "591"
	}, {
		"cityName": "Botswana",
		"pinyin": "Botswana",
		"py": "bw",
		"code": "267"
	}, {
		"cityName": "Brazil",
		"pinyin": "Brazil",
		"py": "br",
		"code": "55"
	}, {
		"cityName": "Brunei",
		"pinyin": "Brunei",
		"py": "bn",
		"code": "673"
	}, {
		"cityName": "Burkina-faso",
		"pinyin": "Burkina-faso",
		"py": "bf",
		"code": "226"
	}, {
		"cityName": "Burma",
		"pinyin": "Burma",
		"py": "bu",
		"code": "95"
	}, {
		"cityName": "Burundi",
		"pinyin": "Burundi",
		"py": "bi",
		"code": "257"
	}, {
		"cityName": "Cameroon",
		"pinyin": "Cameroon",
		"py": "cm",
		"code": "237"
	}, {
		"cityName": "Canada",
		"pinyin": "Canada",
		"py": "ca",
		"code": "1"
	}, {
		"cityName": "Cayman is.",
		"pinyin": "Cayman is.",
		"py": "ca",
		"code": "1345"
	}, {
		"cityName": "Central african republic",
		"pinyin": "Central african republic",
		"py": "cf",
		"code": "236"
	}, {
		"cityName": "Chad",
		"pinyin": "Chad",
		"py": "ch",
		"code": "235"
	}, {
		"cityName": "Chile",
		"pinyin": "Chile",
		"py": "cl",
		"code": "56"
	}, {
		"cityName": "China",
		"pinyin": "China",
		"py": "cn",
		"code": "86"
	}, {
		"cityName": "Colombia",
		"pinyin": "Colombia",
		"py": "co",
		"code": "57"
	}, {
		"cityName": "Congo",
		"pinyin": "Congo",
		"py": "cg",
		"code": "242"
	}, {
		"cityName": "Cook is.",
		"pinyin": "Cook is.",
		"py": "ck",
		"code": "682"
	}, {
		"cityName": "Costa rica",
		"pinyin": "Costa rica",
		"py": "cr",
		"code": "506"
	}, {
		"cityName": "Cuba",
		"pinyin": "Cuba",
		"py": "cu",
		"code": "53"
	}, {
		"cityName": "Cyprus",
		"pinyin": "Cyprus",
		"py": "cy",
		"code": "357"
	}, {
		"cityName": "Czech republic",
		"pinyin": "Czech republic",
		"py": "cz",
		"code": "420"
	}, {
		"cityName": "Denmark",
		"pinyin": "Denmark",
		"py": "dk",
		"code": "45"
	}, {
		"cityName": "Djibouti",
		"pinyin": "Djibouti",
		"py": "dj",
		"code": "253"
	}, {
		"cityName": "Dominica rep.",
		"pinyin": "Dominica rep.",
		"py": "do",
		"code": "1890"
	}, {
		"cityName": "Ecuador",
		"pinyin": "Ecuador",
		"py": "ec",
		"code": "593"
	}, {
		"cityName": "Egypt",
		"pinyin": "Egypt",
		"py": "eg",
		"code": "20"
	}, {
		"cityName": "Ei salvador",
		"pinyin": "Ei salvador",
		"py": "ei",
		"code": "503"
	}, {
		"cityName": "Estonia",
		"pinyin": "Estonia",
		"py": "ee",
		"code": "372"
	}, {
		"cityName": "Ethiopia",
		"pinyin": "Ethiopia",
		"py": "et",
		"code": "251"
	}, {
		"cityName": "Fiji",
		"pinyin": "Fiji",
		"py": "fj",
		"code": "679"
	}, {
		"cityName": "Finland",
		"pinyin": "Finland",
		"py": "fi",
		"code": "358"
	}, {
		"cityName": "France",
		"pinyin": "France",
		"py": "fr",
		"code": "33"
	}, {
		"cityName": "French guiana",
		"pinyin": "French guiana",
		"py": "fr",
		"code": "594"
	}, {
		"cityName": "Gabon",
		"pinyin": "Gabon",
		"py": "ga",
		"code": "241"
	}, {
		"cityName": "Gambia",
		"pinyin": "Gambia",
		"py": "gm",
		"code": "220"
	}, {
		"cityName": "Georgia",
		"pinyin": "Georgia",
		"py": "ge",
		"code": "995"
	}, {
		"cityName": "Germany",
		"pinyin": "Germany",
		"py": "ge",
		"code": "49"
	}, {
		"cityName": "Ghana",
		"pinyin": "Ghana",
		"py": "gh",
		"code": "233"
	}, {
		"cityName": "Gibraltar",
		"pinyin": "Gibraltar",
		"py": "gi",
		"code": "350"
	}, {
		"cityName": "Greece",
		"pinyin": "Greece",
		"py": "gr",
		"code": "30"
	}, {
		"cityName": "Grenada",
		"pinyin": "Grenada",
		"py": "gd",
		"code": "1809"
	}, {
		"cityName": "Guam",
		"pinyin": "Guam",
		"py": "gu",
		"code": "1671"
	}, {
		"cityName": "Guatemala",
		"pinyin": "Guatemala",
		"py": "gt",
		"code": "502"
	}, {
		"cityName": "Guinea",
		"pinyin": "Guinea",
		"py": "gn",
		"code": "224"
	}, {
		"cityName": "Guyana",
		"pinyin": "Guyana",
		"py": "gy",
		"code": "592"
	}, {
		"cityName": "Haiti",
		"pinyin": "Haiti",
		"py": "ht",
		"code": "509"
	}, {
		"cityName": "Honduras",
		"pinyin": "Honduras",
		"py": "hn",
		"code": "504"
	}, {
		"cityName": "Hungary",
		"pinyin": "Hungary",
		"py": "hu",
		"code": "36"
	}, {
		"cityName": "Iceland",
		"pinyin": "Iceland",
		"py": "is",
		"code": "354"
	}, {
		"cityName": "India",
		"pinyin": "India",
		"py": "in",
		"code": "91"
	}, {
		"cityName": "Indonesia",
		"pinyin": "Indonesia",
		"py": "id",
		"code": "62"
	}, {
		"cityName": "Iran",
		"pinyin": "Iran",
		"py": "ir",
		"code": "98"
	}, {
		"cityName": "Iraq",
		"pinyin": "Iraq",
		"py": "iq",
		"code": "964"
	}, {
		"cityName": "Ireland",
		"pinyin": "Ireland",
		"py": "ie",
		"code": "353"
	}, {
		"cityName": "Israel",
		"pinyin": "Israel",
		"py": "il",
		"code": "972"
	}, {
		"cityName": "Italy",
		"pinyin": "Italy",
		"py": "it",
		"code": "39"
	}, {
		"cityName": "Ivory coast",
		"pinyin": "Ivory coast",
		"py": "Ivo",
		"code": "225"
	}, {
		"cityName": "Jamaica",
		"pinyin": "Jamaica",
		"py": "jm",
		"code": "1876"
	}, {
		"cityName": "Japan",
		"pinyin": "Japan",
		"py": "jp",
		"code": "81"
	}, {
		"cityName": "Jordan",
		"pinyin": "Jordan",
		"py": "jo",
		"code": "962"
	}, {
		"cityName": "Kampuchea",
		"pinyin": "Kampuchea",
		"py": "kh",
		"code": "855"
	}, {
		"cityName": "Kazakstan",
		"pinyin": "Kazakstan",
		"py": "kz",
		"code": "327"
	}, {
		"cityName": "Kenya",
		"pinyin": "Kenya",
		"py": "ke",
		"code": "254"
	}, {
		"cityName": "Korea",
		"pinyin": "Korea",
		"py": "kr",
		"code": "82"
	}, {
		"cityName": "Kuwait",
		"pinyin": "Kuwait",
		"py": "kw",
		"code": "965"
	}, {
		"cityName": "Kyrgyzstan",
		"pinyin": "Kyrgyzstan",
		"py": "kg",
		"code": "331"
	}, {
		"cityName": "Laos",
		"pinyin": "Laos",
		"py": "la",
		"code": "856"
	}, {
		"cityName": "Latvia",
		"pinyin": "Latvia",
		"py": "lv",
		"code": "371"
	}, {
		"cityName": "Lebanon",
		"pinyin": "Lebanon",
		"py": "lb",
		"code": "961"
	}, {
		"cityName": "Lesotho",
		"pinyin": "Lesotho",
		"py": "ls",
		"code": "266"
	}, {
		"cityName": "Liberia",
		"pinyin": "Liberia",
		"py": "lr",
		"code": "231"
	}, {
		"cityName": "Libya",
		"pinyin": "Libya",
		"py": "ly",
		"code": "218"
	}, {
		"cityName": "Liechtenstein",
		"pinyin": "Liechtenstein",
		"py": "li",
		"code": "423"
	}, {
		"cityName": "Lithuania",
		"pinyin": "Lithuania",
		"py": "lt",
		"code": "370"
	}, {
		"cityName": "Luxembourg",
		"pinyin": "Luxembourg",
		"py": "lu",
		"code": "352"
	}, {
		"cityName": "Macao",
		"pinyin": "Macao",
		"py": "mo",
		"code": "853"
	}, {
		"cityName": "Madagascar",
		"pinyin": "Madagascar",
		"py": "mg",
		"code": "261"
	}, {
		"cityName": "Malawi",
		"pinyin": "Malawi",
		"py": "mw",
		"code": "265"
	}, {
		"cityName": "Malaysia",
		"pinyin": "Malaysia",
		"py": "my",
		"code": "60"
	}, {
		"cityName": "Maldives",
		"pinyin": "Maldives",
		"py": "mv",
		"code": "960"
	}, {
		"cityName": "Mali",
		"pinyin": "Mali",
		"py": "ml",
		"code": "223"
	}, {
		"cityName": "Malta",
		"pinyin": "Malta",
		"py": "mt",
		"code": "356"
	}, {
		"cityName": "Mariana is",
		"pinyin": "Mariana is",
		"py": "maliyanaqundao",
		"code": "1670"
	}, {
		"cityName": "Martinique",
		"pinyin": "Martinique",
		"py": "matinike",
		"code": "596"
	}, {
		"cityName": "Mauritius",
		"pinyin": "Mauritius",
		"py": "mu",
		"code": "230"
	}, {
		"cityName": "Mexico",
		"pinyin": "Mexico",
		"py": "mx",
		"code": "52"
	}, {
		"cityName": "Moldova republic of",
		"pinyin": "Moldova republic of",
		"py": "md",
		"code": "373"
	}, {
		"cityName": "Monaco",
		"pinyin": "Monaco",
		"py": "mc",
		"code": "377"
	}, {
		"cityName": "Mongolia",
		"pinyin": "Mongolia",
		"py": "mn",
		"code": "976"
	}, {
		"cityName": "Montserrat is",
		"pinyin": "Montserrat is",
		"py": "ms",
		"code": "1664"
	}, {
		"cityName": "Morocco",
		"pinyin": "Morocco",
		"py": "ma",
		"code": "212"
	}, {
		"cityName": "Mozambique",
		"pinyin": "Mozambique",
		"py": "mz",
		"code": "258"
	}, {
		"cityName": "Namibia",
		"pinyin": "Namibia",
		"py": "na",
		"code": "264"
	}, {
		"cityName": "Nauru",
		"pinyin": "Nauru",
		"py": "nr",
		"code": "674"
	}, {
		"cityName": "Nepal",
		"pinyin": "Nepal",
		"py": "np",
		"code": "977"
	}, {
		"cityName": "Netheriands antilles",
		"pinyin": "Netheriands antilles",
		"py": "ne",
		"code": "599"
	}, {
		"cityName": "Netherlands",
		"pinyin": "Netherlands",
		"py": "nl",
		"code": "31"
	}, {
		"cityName": "New zealand",
		"pinyin": "New zealand",
		"py": "nz",
		"code": "64"
	}, {
		"cityName": "Nicaragua",
		"pinyin": "Nicaragua",
		"py": "ni",
		"code": "505"
	}, {
		"cityName": "Niger",
		"pinyin": "Niger",
		"py": "ne",
		"code": "227"
	}, {
		"cityName": "Nigeria",
		"pinyin": "Nigeria",
		"py": "ng",
		"code": "234"
	}, {
		"cityName": "North korea",
		"pinyin": "North korea",
		"py": "nk",
		"code": "850"
	}, {
		"cityName": "Norway",
		"pinyin": "Norway",
		"py": "no",
		"code": "47"
	}, {
		"cityName": "Oman",
		"pinyin": "Oman",
		"py": "om",
		"code": "968"
	}, {
		"cityName": "Pakistan",
		"pinyin": "Pakistan",
		"py": "pk",
		"code": "92"
	}, {
		"cityName": "Panama",
		"pinyin": "Panama",
		"py": "pa",
		"code": "507"
	}, {
		"cityName": "Papua new cuinea",
		"pinyin": "Papua new cuinea",
		"py": "pg",
		"code": "675"
	}, {
		"cityName": "Paraguay",
		"pinyin": "Paraguay",
		"py": "py",
		"code": "595"
	}, {
		"cityName": "Peru",
		"pinyin": "Peru",
		"py": "pe",
		"code": "51"
	}, {
		"cityName": "Philippines",
		"pinyin": "Philippines",
		"py": "ph",
		"code": "63"
	}, {
		"cityName": "Poland",
		"pinyin": "Poland",
		"py": "pl",
		"code": "48"
	}, {
		"cityName": "French polynesia",
		"pinyin": "French polynesia",
		"py": "pf",
		"code": "689"
	}, {
		"cityName": "Portugal",
		"pinyin": "Portugal",
		"py": "pt",
		"code": "351"
	}, {
		"cityName": "Puerto rico",
		"pinyin": "Puerto rico",
		"py": "pr",
		"code": "1787"
	}, {
		"cityName": "Qatar",
		"pinyin": "Qatar",
		"py": "qa",
		"code": "974"
	}, {
		"cityName": "Reunion",
		"pinyin": "Reunion",
		"py": "re",
		"code": "262"
	}, {
		"cityName": "Romania",
		"pinyin": "Romania",
		"py": "ro",
		"code": "40"
	}, {
		"cityName": "Russia",
		"pinyin": "Russia",
		"py": "ru",
		"code": "7"
	}, {
		"cityName": "Saint lueia",
		"pinyin": "Saint lueia",
		"py": "sa",
		"code": "1758"
	}, {
		"cityName": "Saint vincent",
		"pinyin": "Saint vincent",
		"py": "vc",
		"code": "1784"
	}, {
		"cityName": "Samoa eastern",
		"pinyin": "Samoa eastern",
		"py": "sa",
		"code": "684"
	}, {
		"cityName": "Samoa western",
		"pinyin": "Samoa western",
		"py": "sa",
		"code": "685"
	}, {
		"cityName": "San marino",
		"pinyin": "San marino",
		"py": "sm",
		"code": "378"
	}, {
		"cityName": "Sao tome and princip",
		"pinyin": "Sao tome and principe",
		"py": "st",
		"code": "239"
	}, {
		"cityName": "Saudi arabia",
		"pinyin": "Saudi arabia",
		"py": "sa",
		"code": "966"
	}, {
		"cityName": "Senegal",
		"pinyin": "Senegal",
		"py": "sn",
		"code": "221"
	}, {
		"cityName": "Seychelles",
		"pinyin": "Seychelles",
		"py": "sc",
		"code": "248"
	}, {
		"cityName": "Sierra leone",
		"pinyin": "Sierra leone",
		"py": "sl",
		"code": "232"
	}, {
		"cityName": "Singapore",
		"pinyin": "Singapore",
		"py": "sg",
		"code": "65"
	}, {
		"cityName": "Slovakia",
		"pinyin": "Slovakia",
		"py": "sk",
		"code": "421"
	}, {
		"cityName": "Solomon is",
		"pinyin": "Solomon is",
		"py": "sb",
		"code": "677"
	}, {
		"cityName": "Somali",
		"pinyin": "Somali",
		"py": "so",
		"code": "252"
	}, {
		"cityName": "South africa",
		"pinyin": "South africa",
		"py": "so",
		"code": "27"
	}, {
		"cityName": "Spain",
		"pinyin": "Spain",
		"py": "sp",
		"code": "34"
	}, {
		"cityName": "Sri lanka",
		"pinyin": "Sri lanka",
		"py": "sr",
		"code": "94"
	}, {
		"cityName": "St.lucia",
		"pinyin": "St.lucia",
		"py": "st",
		"code": "1758"
	}, {
		"cityName": "St.vincent",
		"pinyin": "St.vincent",
		"py": "vc",
		"code": "1784"
	}, {
		"cityName": "Sudan",
		"pinyin": "Sudan",
		"py": "sd",
		"code": "249"
	}, {
		"cityName": "Swaziland",
		"pinyin": "Swaziland",
		"py": "sz",
		"code": "268"
	}, {
		"cityName": "Sweden",
		"pinyin": "Sweden",
		"py": "se",
		"code": "46"
	}, {
		"cityName": "Switzerland",
		"pinyin": "Switzerland",
		"py": "sw",
		"code": "41"
	}, {
		"cityName": "Syria",
		"pinyin": "Syria",
		"py": "sy",
		"code": "963"
	}, {
		"cityName": "Tajikstan",
		"pinyin": "Tajikstan",
		"py": "tj",
		"code": "992"
	}, {
		"cityName": "Tanzania",
		"pinyin": "Tanzania",
		"py": "tz",
		"code": "255"
	}, {
		"cityName": "Thailand",
		"pinyin": "Thailand",
		"py": "th",
		"code": "66"
	}, {
		"cityName": "Togo",
		"pinyin": "Togo",
		"py": "tg",
		"code": "228"
	}, {
		"cityName": "Tonga",
		"pinyin": "Tonga",
		"py": "to",
		"code": "676"
	}, {
		"cityName": "Trinidad and tobago",
		"pinyin": "Trinidad and tobago",
		"py": "tt",
		"code": "1809"
	}, {
		"cityName": "Tunisia",
		"pinyin": "Tunisia",
		"py": "tn",
		"code": "216"
	}, {
		"cityName": "Turkey",
		"pinyin": "Turkey",
		"py": "tr",
		"code": "90"
	}, {
		"cityName": "Turkmenistan",
		"pinyin": "Turkmenistan",
		"py": "tm",
		"code": "993"
	}, {
		"cityName": "Uganda",
		"pinyin": "Uganda",
		"py": "ug",
		"code": "256"
	}, {
		"cityName": "Ukraine",
		"pinyin": "Ukraine",
		"py": "ua",
		"code": "380"
	}, {
		"cityName": "United arab emirates",
		"pinyin": "United arab emirates",
		"py": "un",
		"code": "971"
	}, {
		"cityName": "United kiongdom",
		"pinyin": "united kiongdom",
		"py": "un",
		"code": "44"
	}, {
		"cityName": "America",
		"pinyin": "America",
		"py": "am",
		"code": "1"
	}, {
		"cityName": "Uruguay",
		"pinyin": "Uruguay",
		"py": "uy",
		"code": "598"
	}, {
		"cityName": "Uzbekistan",
		"pinyin": "Uzbekistan",
		"py": "uz",
		"code": "233"
	}, {
		"cityName": "Venezuela",
		"pinyin": "Venezuela",
		"py": "ve",
		"code": "58"
	}, {
		"cityName": "Uietnam",
		"pinyin": "Uietnam",
		"py": "vn",
		"code": "84"
	}, {
		"cityName": "Yemen",
		"pinyin": "Yemen",
		"py": "ye",
		"code": "967"
	}, {
		"cityName": "Yugoslavia",
		"pinyin": "Yugoslavia",
		"py": "yu",
		"code": "381"
	}, {
		"cityName": "Zimbabwe",
		"pinyin": "Zimbabwe",
		"py": "zw",
		"code": "263"
	}, {
		"cityName": "Zaire",
		"pinyin": "Zaire",
		"py": "zr",
		"code": "243"
	}, {
		"cityName": "Zambia",
		"pinyin": "zambia",
		"py": "zm",
		"code": "260"
	}],
};
