
 {
	hotcity: [{
			cityName: '中国',
			pinyin: 'beijing',
			py: 'bj',
			code: '86'
		},
	
		{
			cityName: '天津',
			pinyin: 'tianjin',
			py: 'tj',
			code: 'tsn'
		},
		{
			cityName: '青岛',
			pinyin: 'qingdao',
			py: 'qd',
			code: 'tao'
		},
		{
			cityName: '南京',
			pinyin: 'nanjing',
			py: 'nj',
			code: 'nkg'
		},
		{
			cityName: '杭州',
			pinyin: 'hangzhou',
			py: 'hz',
			code: 'hgh'
		},
		{
			cityName: '厦门',
			pinyin: 'xiamen',
			py: 'xm',
			code: 'xmn'
		},
		{
			cityName: '成都',
			pinyin: 'chengdu',
			py: 'cd',
			code: 'ctu'
		},
		{
			cityName: '深圳',
			pinyin: 'shenzhen',
			py: 'sz',
			code: 'szx'
		},
		{
			cityName: '广州',
			pinyin: 'guangzhou',
			py: 'gz',
			code: 'can'
		},
		{
			cityName: '沈阳',
			pinyin: 'shenyang',
			py: 'sy',
			code: 'she'
		},
		{
			cityName: '武汉',
			pinyin: 'wuhan',
			py: 'wh',
			code: 'wuh'
		}
	],
	cities: [{
		"cityName": "安哥拉",
		"pinyin": "angela",
		"py": "agl",
		"code": "244",
		// "sum":100
	}, {
		"cityName": "阿富汗",
		"pinyin": "afuhan",
		"py": "afh",
		"code": "93"
	}, {
		"cityName": "阿拉伯联合酋长国",
		"pinyin": "alabolianheqiuzhangguo",
		"py": "alblhqzg",
		"code": "971"
	}, {
		"cityName": "阿尔巴尼亚",
		"pinyin": "aerbaniya",
		"py": "aebny",
		"code": "355"
	}, {
		"cityName": "阿尔及利亚",
		"pinyin": "aerjiliya",
		"py": "aejly",
		"code": "213"
	}, {
		"cityName": "安道尔共和国",
		"pinyin": "andaoergongheguo",
		"py": "adeghg",
		"code": "376"
	}, {
		"cityName": "安圭拉岛",
		"pinyin": "anguiladao",
		"py": "agld",
		"code": "1264"
	}, {
		"cityName": "安提瓜和巴布达",
		"pinyin": "antiguahebabuda",
		"py": "atghbbd",
		"code": "1268"
	}, {
		"cityName": "阿根廷",
		"pinyin": "agenting",
		"py": "agt",
		"code": "54"
	}, {
		"cityName": "阿曼",
		"pinyin": "aman",
		"py": "am",
		"code": "968"
	}, {
		"cityName": "阿森松",
		"pinyin": "asensong",
		"py": "ass",
		"code": "247"
	}, {
		"cityName": "澳大利亚",
		"pinyin": "aodaliya",
		"py": "adly",
		"code": "61"
	}, {
		"cityName": "奥地利",
		"pinyin": "aodili",
		"py": "adl",
		"code": "43"
	}, {
		"cityName": "阿塞拜疆",
		"pinyin": "asaibaijiang",
		"py": "asbj",
		"code": "994"
	}, {
		"cityName": "埃及",
		"pinyin": "aiji",
		"py": "aj",
		"code": "20"
	}, {
		"cityName": "爱尔兰",
		"pinyin": "aierlan",
		"py": "ael",
		"code": "353"
	}, {
		"cityName": "爱沙尼亚",
		"pinyin": "aishaniya",
		"py": "asny",
		"code": "372"
	}, {
		"cityName": "埃塞俄比亚",
		"pinyin": "aisaiebiya",
		"py": "aseby",
		"code": "251"
	}, {
		"cityName": "巴哈马",
		"pinyin": "bahama",
		"py": "bhm",
		"code": "1242"
	}, {
		"cityName": "巴林",
		"pinyin": "balin",
		"py": "bl",
		"code": "973"
	}, {
		"cityName": "巴巴多斯",
		"pinyin": "babaduosi",
		"py": "bbds",
		"code": "1246"
	}, {
		"cityName": "白俄罗斯",
		"pinyin": "baieluosi",
		"py": "bels",
		"code": "375"
	}, {
		"cityName": "比利时",
		"pinyin": "bilishi",
		"py": "bls",
		"code": "32	"
	}, {
		"cityName": "伯利兹",
		"pinyin": "bolizi",
		"py": "blz",
		"code": "501"
	}, {
		"cityName": "波兰",
		"pinyin": "bolan",
		"py": "bl",
		"code": "48"
	}, {
		"cityName": "贝宁",
		"pinyin": "beining",
		"py": "bn",
		"code": "229"
	}, {
		"cityName": "百慕大群岛",
		"pinyin": "baimudaqundao",
		"py": "bmdqd",
		"code": "1441"
	}, {
		"cityName": "巴基斯坦",
		"pinyin": "bajisitan",
		"py": "bjst",
		"code": "92"
	}, {
		"cityName": "巴拿马",
		"pinyin": "banama",
		"py": "bnm",
		"code": "507"
	}, {
		"cityName": "巴布亚新几内亚",
		"pinyin": "babuyaxinjineiya",
		"py": "bbyxjny",
		"code": "675"
	}, {
		"cityName": "巴拉圭",
		"pinyin": "balaigui",
		"py": "blg",
		"code": "595"
	}, {
		"cityName": "秘鲁",
		"pinyin": "bilu",
		"py": "bl",
		"code": "51"
	}, {
		"cityName": "玻利维亚",
		"pinyin": "boliweiya",
		"py": "blwy",
		"code": "591"
	}, {
		"cityName": "博茨瓦纳",
		"pinyin": "bociwana",
		"py": "bcwn",
		"code": "267"
	}, {
		"cityName": "波多黎各",
		"pinyin": "boduolige",
		"py": "bdlg",
		"code": "1787"
	}, {
		"cityName": "巴西",
		"pinyin": "baxi",
		"py": "bx",
		"code": "55"
	}, {
		"cityName": "冰岛",
		"pinyin": "bingdao",
		"py": "bd",
		"code": "354"
	}, {
		"cityName": "布基纳法索",
		"pinyin": "bujinafasuo",
		"py": "bjnfs",
		"code": "226"
	}, {
		"cityName": "布隆迪",
		"pinyin": "bulongdi",
		"py": "bld",
		"code": "257"
	}, {
		"cityName": "朝鲜",
		"pinyin": "chaoxian",
		"py": "cx",
		"code": "850"
	}, {
		"cityName": "丹麦",
		"pinyin": "danmai",
		"py": "dm",
		"code": "45"
	}, {
		"cityName": "德国",
		"pinyin": "deguo",
		"py": "dg",
		"code": "49"
	}, {
		"cityName": "多米尼加共和国",
		"pinyin": "duominijiagongheguo",
		"py": "dmnjghg",
		"code": "1890"
	}, {
		"cityName": "多哥",
		"pinyin": "duoge",
		"py": "dg",
		"code": "228"
	}, {
		"cityName": "东萨摩亚(美)",
		"pinyin": "dongsamoya(mei)",
		"py": "dsmy",
		"code": "684"
	}, {
		"cityName": "厄瓜多尔",
		"pinyin": "eguaduoer",
		"py": "egde",
		"code": "593"
	}, {
		"cityName": "俄罗斯",
		"pinyin": "eluosi",
		"py": "els",
		"code": "7"
	}, {
		"cityName": "法国",
		"pinyin": "faguo",
		"py": "fg",
		"code": "33"
	}, {
		"cityName": "法属圭亚那",
		"pinyin": "fashuguiyana",
		"py": "fsgyn",
		"code": "594"
	}, {
		"cityName": "法属玻利尼西亚",
		"pinyin": "fashubolinixiya",
		"py": "fsblnxy",
		"code": "689"
	}, {
		"cityName": "斐济",
		"pinyin": "feiji",
		"py": "fj",
		"code": "679"
	}, {
		"cityName": "菲律宾",
		"pinyin": "feilvbin",
		"py": "flb",
		"code": "63"
	}, {
		"cityName": "芬兰",
		"pinyin": "fenlan",
		"py": "fl",
		"code": "358"
	}, {
		"cityName": "冈比亚",
		"pinyin": "gangbiya",
		"py": "gby",
		"code": "220"
	}, {
		"cityName": "哥斯达黎加",
		"pinyin": "gesidalijia",
		"py": "gsdlj",
		"code": "506"
	}, {
		"cityName": "古巴",
		"pinyin": "guba",
		"py": "gb",
		"code": "53"
	}, {
		"cityName": "哥伦比亚",
		"pinyin": "gelunbiya",
		"py": "glby",
		"code": "57"
	}, {
		"cityName": "格鲁吉亚",
		"pinyin": "gelujiya",
		"py": "gljy",
		"code": "995"
	}, {
		"cityName": "刚果",
		"pinyin": "gangguo",
		"py": "gg",
		"code": "242"
	}, {
		"cityName": "格林纳达",
		"pinyin": "gelinnada",
		"py": "glnd",
		"code": "1809"
	}, {
		"cityName": "关岛",
		"pinyin": "guandao",
		"py": "gd",
		"code": "1671"
	}, {
		"cityName": "圭亚那",
		"pinyin": "guiyana",
		"py": "gyn",
		"code": "592"
	}, {
		"cityName": "韩国",
		"pinyin": "hanguo",
		"py": "hg",
		"code": "82"
	}, {
		"cityName": "海地",
		"pinyin": "haidi",
		"py": "hd",
		"code": "509"
	}, {
		"cityName": "哈萨克斯坦",
		"pinyin": "hasakesitan",
		"py": "hskst",
		"code": "327"
	}, {
		"cityName": "荷属安的列斯",
		"pinyin": "heshuandeliesi",
		"py": "hsadls",
		"code": "599"
	}, {
		"cityName": "荷兰",
		"pinyin": "helan",
		"py": "hl",
		"code": "31"
	}, {
		"cityName": "洪都拉斯",
		"pinyin": "hongdulasi",
		"py": "hdls",
		"code": "504"
	}, {
		"cityName": "吉尔吉斯坦",
		"pinyin": "jierjisitan",
		"py": "jejst",
		"code": "331"
	}, {
		"cityName": "加纳",
		"pinyin": "jiana",
		"py": "jn",
		"code": "233"
	}, {
		"cityName": "加蓬",
		"pinyin": "jiapeng",
		"py": "jp",
		"code": "241"
	}, {
		"cityName": "捷克",
		"pinyin": "jieke",
		"py": "jk",
		"code": "420"
	}, {
		"cityName": "加拿大",
		"pinyin": "jianada",
		"py": "jnd",
		"code": "1"
	}, {
		"cityName": "几内亚",
		"pinyin": "jineiya",
		"py": "jny",
		"code": "224"
	}, {
		"cityName": "吉布提",
		"pinyin": "jibuti",
		"py": "jbt",
		"code": "253"
	}, {
		"cityName": "柬埔寨",
		"pinyin": "jianpuzhai",
		"py": "jpz",
		"code": "855"
	}, {
		"cityName": "津巴布韦",
		"pinyin": "jingbabuwei",
		"py": "jbbw",
		"code": "263"
	}, {
		"cityName": "喀麦隆",
		"pinyin": "kamailong",
		"py": "kml",
		"code": "237"
	}, {
		"cityName": "开曼群岛",
		"pinyin": "kaimanqundao",
		"py": "kmqd",
		"code": "1345"
	}, {
		"cityName": "卡塔尔",
		"pinyin": "kataer",
		"py": "kte",
		"code": "974"
	}, {
		"cityName": "肯尼亚",
		"pinyin": "kenniya",
		"py": "kny",
		"code": "254"
	}, {
		"cityName": "科特迪瓦",
		"pinyin": "ketediwa",
		"py": "ktdw",
		"code": "225"
	}, {
		"cityName": "科威特",
		"pinyin": "keweite",
		"py": "kwt",
		"code": "965"
	}, {
		"cityName": "库克群岛",
		"pinyin": "kukequndao",
		"py": "kkqd",
		"code": "682"
	}, {
		"cityName": "老挝",
		"pinyin": "laowo",
		"py": "lw",
		"code": "856"
	}, {
		"cityName": "拉脱维亚",
		"pinyin": "latuoweiya",
		"py": "ltwy",
		"code": "371"
	}, {
		"cityName": "黎巴嫩",
		"pinyin": "libanen",
		"py": "lbn",
		"code": "961"
	}, {
		"cityName": "瑙鲁",
		"pinyin": "laolu",
		"py": "ll",
		"code": "674"
	}, {
		"cityName": "莱索托",
		"pinyin": "laisuotuo",
		"py": "lst",
		"code": "266"
	}, {
		"cityName": "利比里亚",
		"pinyin": "libiliya",
		"py": "lbly",
		"code": "231"
	}, {
		"cityName": "利比亚",
		"pinyin": "libiya",
		"py": "lby",
		"code": "218"
	}, {
		"cityName": "列支敦士登",
		"pinyin": "liezhidunshideng",
		"py": "lzdsd",
		"code": "423"
	}, {
		"cityName": "立陶宛",
		"pinyin": "litaowan",
		"py": "ltw",
		"code": "370"
	}, {
		"cityName": "留尼旺",
		"pinyin": "liuniwang",
		"py": "lnw",
		"code": "262"
	}, {
		"cityName": "卢森堡",
		"pinyin": "lusenbao",
		"py": "lsb",
		"code": "352"
	}, {
		"cityName": "罗马尼亚",
		"pinyin": "luomaniya",
		"py": "lmny",
		"code": "40"
	}, {
		"cityName": "马达加斯加",
		"pinyin": "madajiasijia",
		"py": "mdjsj",
		"code": "261"
	}, {
		"cityName": "孟加拉国",
		"pinyin": "mengjialaguo",
		"py": "mjlg",
		"code": "880"
	}, {
		"cityName": "马拉维",
		"pinyin": "malawei",
		"py": "mlw",
		"code": "265"
	}, {
		"cityName": "马来西亚",
		"pinyin": "malaixiya",
		"py": "mlxy",
		"code": "60"
	}, {
		"cityName": "马尔代夫",
		"pinyin": "maerdaifu",
		"py": "medf",
		"code": "960"
	}, {
		"cityName": "马里",
		"pinyin": "mali",
		"py": "ml",
		"code": "223"
	}, {
		"cityName": "马耳他",
		"pinyin": "maerta",
		"py": "met",
		"code": "356"
	}, {
		"cityName": "美国",
		"pinyin": "meiguo",
		"py": "mg",
		"code": "1"
	}, {
		"cityName": "马里亚那群岛",
		"pinyin": "maliyanaqundao",
		"py": "mlynqd",
		"code": "1670"
	}, {
		"cityName": "马提尼克",
		"pinyin": "matinike",
		"py": "mtnk",
		"code": "596"
	}, {
		"cityName": "缅甸",
		"pinyin": "miandian",
		"py": "md",
		"code": "95"
	}, {
		"cityName": "毛里求斯",
		"pinyin": "maoliqiusi",
		"py": "mlqs",
		"code": "230"
	}, {
		"cityName": "墨西哥",
		"pinyin": "moxige",
		"py": "mxg",
		"code": "52"
	}, {
		"cityName": "摩尔多瓦",
		"pinyin": "moerduowa",
		"py": "medw",
		"code": "373"
	}, {
		"cityName": "摩纳哥",
		"pinyin": "monage",
		"py": "mng",
		"code": "377"
	}, {
		"cityName": "蒙古",
		"pinyin": "menggu",
		"py": "mg",
		"code": "976"
	}, {
		"cityName": "蒙特塞拉特岛",
		"pinyin": "mengtesailatedao",
		"py": "mtsltd",
		"code": "1664"
	}, {
		"cityName": "摩洛哥",
		"pinyin": "moluoge",
		"py": "mlg",
		"code": "212"
	}, {
		"cityName": "莫桑比克",
		"pinyin": "mosangbike",
		"py": "msbk",
		"code": "258"
	}, {
		"cityName": "纳米比亚",
		"pinyin": "namibia",
		"py": "nmby",
		"code": "264"
	}, {
		"cityName": "尼泊尔",
		"pinyin": "niboer",
		"py": "nbe",
		"code": "977"
	}, {
		"cityName": "南非",
		"pinyin": "nanfei",
		"py": "nf",
		"code": "27"
	}, {
		"cityName": "南斯拉夫",
		"pinyin": "nansilafu",
		"py": "nslf",
		"code": "381"
	}, {
		"cityName": "尼加拉瓜",
		"pinyin": "nijialagua",
		"py": "njlg",
		"code": "505"
	}, {
		"cityName": "尼日尔",
		"pinyin": "nirier",
		"py": "nre",
		"code": "227"
	}, {
		"cityName": "尼日利亚",
		"pinyin": "niriliya",
		"py": "nrly",
		"code": "234"
	}, {
		"cityName": "挪威",
		"pinyin": "nuowei",
		"py": "nw",
		"code": "47"
	}, {
		"cityName": "葡萄牙",
		"pinyin": "putaoya",
		"py": "pty",
		"code": "351"
	}, {
		"cityName": "日本",
		"pinyin": "riben",
		"py": "rb",
		"code": "81"
	}, {
		"cityName": "瑞典",
		"pinyin": "ruidian",
		"py": "rd",
		"code": "46"
	}, {
		"cityName": "瑞士",
		"pinyin": "ruishi",
		"py": "rs",
		"code": "41"
	}, {
		"cityName": "塞浦路斯",
		"pinyin": "saipulusi",
		"py": "spls",
		"code": "357"
	},{
		"cityName": "圣卢西亚",
		"pinyin": "shengluxika",
		"py": "slxy",
		"code": "1758"
	}, {
		"cityName": "圣文森特",
		"pinyin": "shengwensente",
		"py": "swst",
		"code": "1784"
	}, {
		"cityName": "圣文森特岛",
		"pinyin": "shengwensentedao",
		"py": "swstd",
		"code": "1784"
	},  {
		"cityName": "圣马力诺",
		"pinyin": "shengmalinuo",
		"py": "smln",
		"code": "378"
	}, {
		"cityName": "圣多美和普林西比",
		"pinyin": "shengduomeihepulinxibi",
		"py": "sdmhplxb",
		"code": "239"
	}, {
		"cityName": "沙特阿拉伯",
		"pinyin": "shatealabo",
		"py": "stalb",
		"code": "966"
	}, {
		"cityName": "塞内加尔",
		"pinyin": "saineijiaer",
		"py": "snje",
		"code": "221"
	}, {
		"cityName": "塞舌尔",
		"pinyin": "saisheer",
		"py": "sse",
		"code": "248"
	}, {
		"cityName": "塞拉利昂",
		"pinyin": "sailaliang",
		"py": "slla",
		"code": "232"
	}, {
		"cityName": "斯洛伐克",
		"pinyin": "siluofake",
		"py": "slfk",
		"code": "421"
	}, {
		"cityName": "所罗门群岛",
		"pinyin": "suoluomenqundao",
		"py": "slmqd",
		"code": "677"
	}, {
		"cityName": "索马里",
		"pinyin": "suomali",
		"py": "sml",
		"code": "252"
	}, {
		"cityName": "斯里兰卡",
		"pinyin": "sililanka",
		"py": "sllk",
		"code": "94"
	}, {
		"cityName": "圣卢西亚",
		"pinyin": "shengluxiya",
		"py": "slxy",
		"code": "1758"
	}, {
		"cityName": "萨尔瓦多",
		"pinyin": "saerwaduo",
		"py": "sewd",
		"code": "503"
	}, {
		"cityName": "苏丹",
		"pinyin": "sudan",
		"py": "sd",
		"code": "249"
	}, {
		"cityName": "斯威士兰",
		"pinyin": "siweishilan",
		"py": "swsl",
		"code": "268"
	}, {
		"cityName": "塔吉克斯坦",
		"pinyin": "tajikesitan",
		"py": "tjkst",
		"code": "992"
	}, {
		"cityName": "坦桑尼亚",
		"pinyin": "tansangniya",
		"py": "tsny",
		"code": "255"
	}, {
		"cityName": "泰国",
		"pinyin": "taiguo",
		"py": "tg",
		"code": "66"
	}, {
		"cityName": "汤加",
		"pinyin": "tangjia",
		"py": "tj",
		"code": "676"
	}, {
		"cityName": "特立尼达和多巴哥",
		"pinyin": "telinidaheduobage",
		"py": "tlndhdbg",
		"code": "1809"
	}, {
		"cityName": "突尼斯",
		"pinyin": "tunisi",
		"py": "tns",
		"code": "216"
	}, {
		"cityName": "土耳其",
		"pinyin": "tuerqi",
		"py": "teq",
		"code": "90"
	}, {
		"cityName": "土库曼斯坦",
		"pinyin": "tukumansitan",
		"py": "tkmst",
		"code": "993"
	}, {
		"cityName": "文莱",
		"pinyin": "wenlai",
		"py": "wl",
		"code": "673"
	}, {
		"cityName": "危地马拉",
		"pinyin": "weidimala",
		"py": "wdml",
		"code": "502"
	}, {
		"cityName": "委内瑞拉",
		"pinyin": "weineiruila",
		"py": "wnrl",
		"code": "58"
	}, {
		"cityName": "乌干达",
		"pinyin": "wuganda",
		"py": "wgd",
		"code": "256"
	}, {
		"cityName": "乌克兰",
		"pinyin": "wukelan",
		"py": "wkl",
		"code": "380"
	}, {
		"cityName": "乌拉圭",
		"pinyin": "wulagui",
		"py": "wlg",
		"code": "598"
	}, {
		"cityName": "乌兹别克斯坦",
		"pinyin": "wuzibiekesitan",
		"py": "wzbkst",
		"code": "233"
	}, {
		"cityName": "希腊",
		"pinyin": "xila",
		"py": "xl",
		"code": "30"
	}, {
		"cityName": "西班牙",
		"pinyin": "xibanya",
		"py": "xby",
		"code": "34"
	}, {
		"cityName": "新西兰",
		"pinyin": "xinxilan",
		"py": "xxl",
		"code": "64"
	}, {
		"cityName": "新加坡",
		"pinyin": "xinjiapo",
		"py": "xjp",
		"code": "65"
	}, {
		"cityName": "匈牙利",
		"pinyin": "xiongyali",
		"py": "xyl",
		"code": "36"
	}, {
		"cityName": "西萨摩亚",
		"pinyin": "xisamoya",
		"py": "xsmy",
		"code": "685"
	}, {
		"cityName": "叙利亚",
		"pinyin": "xuliya",
		"py": "xly",
		"code": "963"
	}, {
		"cityName": "亚美尼亚",
		"pinyin": "yameiniya",
		"py": "ymny",
		"code": "374"
	}, {
		"cityName": "牙买加",
		"pinyin": "yamaijia",
		"py": "ymj",
		"code": "1876"
	}, {
		"cityName": "越南",
		"pinyin": "yuenan",
		"py": "vn",
		"code": "84"
	}, {
		"cityName": "约旦",
		"pinyin": "yuedan",
		"py": "yd",
		"code": "962"
	}, {
		"cityName": "也门",
		"pinyin": "yemen",
		"py": "ym",
		"code": "967"
	}, {
		"cityName": "以色列",
		"pinyin": "yiselie",
		"py": "ysl",
		"code": "972"
	}, {
		"cityName": "意大利",
		"pinyin": "yidali",
		"py": "ydl",
		"code": "39"
	}, {
		"cityName": "印度",
		"pinyin": "yindu",
		"py": "yd",
		"code": "91"
	}, {
		"cityName": "印度尼西亚",
		"pinyin": "yindunixiya",
		"py": "ydnxy",
		"code": "62"
	}, {
		"cityName": "伊朗",
		"pinyin": "yilang",
		"py": "yl",
		"code": "98"
	}, {
		"cityName": "伊拉克",
		"pinyin": "yilake",
		"py": "ylk",
		"code": "964"
	}, {
		"cityName": "英国",
		"pinyin": "yingguo",
		"py": "yg",
		"code": "44"
	}, {
		"cityName": "赞比亚",
		"pinyin": "zanbiya",
		"py": "zby",
		"code": "260"
	}, {
		"cityName": "中国",
		"pinyin": "zhongguo",
		"py": "zg",
		"code": "86"
	}, {
		"cityName": "中国澳门",
		"pinyin": "zhongguoaomen",
		"py": "zgam",
		"code": "853"
	}, {
		"cityName": "中国台湾",
		"pinyin": "zhongguotaiwan",
		"py": "zgtw",
		"code": "886"
	}, {
		"cityName": "中国香港",
		"pinyin": "zhongguoxianggang",
		"py": "zgxg",
		"code": "852"
	}, {
		"cityName": "乍得",
		"pinyin": "zhade",
		"py": "zd",
		"code": "235"
	}, {
		"cityName": "智利",
		"pinyin": "zhili",
		"py": "zl",
		"code": "56"
	}, {
		"cityName": "中非共和国",
		"pinyin": "zhongfeigongheguo",
		"py": "zfghg",
		"code": "236"
	}, {
		"cityName": "扎伊尔",
		"pinyin": "zhayier",
		"py": "zye",
		"code": "243"
	}, {
		"cityName": "直布罗陀",
		"pinyin": "zhibuluotuo",
		"py": "zblt",
		"code": "350"
	}],
};
